[project]
name = "stt-timing"
version = "0.1.0"
description = "wip"
requires-python = ">=3.13"
dependencies = [
    "speechmatics-voice",
    "pipecat-ai[assemblyai,cartesia,deepgram,runner,silero,speechmatics,webrtc]",
    "matplotlib>=3.7.0",
    "numpy>=1.24.0",
]

[dependency-groups]
dev = [
    "ruff~=0.12.1",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.ruff]
line-length = 100
[tool.ruff.lint]
select = ["I"]

[tool.uv.sources]
speechmatics-voice = { path = "../../../speechmatics-python-sdk/sdk/voice", editable = true }
pipecat-ai = { path = "../../pipecat", editable = true }

[tool.uv]
override-dependencies = [
    "speechmatics-voice[smart]>=0.0.0",
    "pipecat-ai[assemblyai,cartesia,deepgram,runner,silero,speechmatics,webrtc]>=0.0.0",
]
